[project]
name = "fastmcp-template"
version = "0.1.0"
description = "Your Go-to template to learn FastMCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.5",
    "openai[aiohttp]>=2.5.0",
    "openai-agents>=0.4.0",
    "ruff>=0.14.1",
]
